# Generated by Django 4.0.6 on 2022-09-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('posicion', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('goles', models.CharField(max_length=50)),
            ],
        ),
    ]
